# Generated by Django 5.2.7 on 2025-10-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='google_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('identifier', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='google_form_name_1c996f_idx'), models.Index(fields=['identifier'], name='google_form_identif_1cff47_idx'), models.Index(fields=['created_at'], name='google_form_created_0275c0_idx')],
            },
        ),
    ]
