# Generated by Django 5.2.7 on 2025-10-15 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleFormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_id', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='google_form.google_form')),
            ],
            options={
                'unique_together': {('sheet', 'response_id')},
            },
        ),
    ]
