# Generated by Django 5.2.7 on 2025-10-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Title', models.CharField(max_length=255)),
                ('Experience_In_Years', models.TextField()),
                ('Description', models.CharField(max_length=255)),
                ('Job_Type', models.CharField(max_length=100)),
                ('Job_Location', models.CharField(max_length=255)),
                ('no_of_opening', models.IntegerField()),
                ('Skills_Required', models.ManyToManyField(related_name='jobs', to='create_job.skills')),
            ],
            options={
                'db_table': 'job_listings',
            },
        ),
    ]
