# Generated by Django 5.2.7 on 2025-10-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Description',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='Experience_In_Years',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='Job_Location',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='Job_Title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='Job_Type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='no_of_opening',
            field=models.IntegerField(db_index=True),
        ),
    ]
