# Generated by Django 5.2.7 on 2025-11-05 06:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_job', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='add_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.BigIntegerField(auto_created=True, db_index=True, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('Description', models.TextField()),
                ('Salary_range', models.CharField(db_index=True, max_length=100)),
                ('Experience_required', models.CharField(db_index=True, max_length=100)),
                ('no_opening', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('employments_types', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='create_job.department')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
                ('teams', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='create_job.teams')),
            ],
            options={
                'db_table': 'add_job',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title', 'is_active'], name='add_job_title_4a1bfc_idx'), models.Index(fields=['job_id', 'is_active'], name='add_job_job_id_2fbdd0_idx'), models.Index(fields=['teams', 'is_active'], name='add_job_teams_i_9a5f4c_idx'), models.Index(fields=['employments_types', 'is_active'], name='add_job_employm_965ade_idx'), models.Index(fields=['Salary_range', 'Experience_required'], name='add_job_Salary__f11155_idx'), models.Index(fields=['created_at', 'updated_at'], name='add_job_created_6c1c63_idx')],
                'constraints': [models.UniqueConstraint(fields=('job_id',), name='unique_job_id_constraint')],
            },
        ),
    ]
