# Generated by Django 5.2.7 on 2025-11-05 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_job', '0002_add_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_job',
            name='employments_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='create_job.job_types'),
        ),
    ]
