# Generated by Django 5.2.7 on 2025-10-30 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_job', '0003_department_job_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='create_job.department'),
        ),
        migrations.AddField(
            model_name='job',
            name='Target_hire_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='budget',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='Description',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='Job_Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='create_job.job_types'),
        ),
    ]
