# Generated by Django 5.2.7 on 2025-11-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_job', '0003_alter_add_job_employments_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_job',
            name='job_id',
            field=models.BigIntegerField(auto_created=True, db_index=True, editable=False, unique=True),
        ),
    ]
