# Generated by Django 5.2.7 on 2025-11-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_job', '0004_alter_add_job_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_job',
            name='job_id',
            field=models.CharField(db_index=True, editable=False, max_length=20, unique=True),
        ),
    ]
