# Generated by Django 5.2.7 on 2025-10-30 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_job', '0004_job_department_job_target_hire_date_job_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Job_Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create_job.job_types'),
        ),
    ]
