# Generated by Django 5.2.7 on 2025-10-30 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_job', '0005_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Job_Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='create_job.job_types'),
        ),
    ]
