# Generated by Django 5.2.7 on 2025-11-05 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_job', '0005_alter_add_job_job_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='hiring_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_as_hiring_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teams',
            name='hr_team_members',
            field=models.ManyToManyField(blank=True, related_name='teams_as_hr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teams',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='teams',
            index=models.Index(fields=['name'], name='Teams_name_4fe85c_idx'),
        ),
        migrations.AddIndex(
            model_name='teams',
            index=models.Index(fields=['department_types'], name='Teams_departm_76306d_idx'),
        ),
        migrations.AddIndex(
            model_name='teams',
            index=models.Index(fields=['manager'], name='Teams_manager_56c5a1_idx'),
        ),
        migrations.AddIndex(
            model_name='teams',
            index=models.Index(fields=['hiring_manager'], name='Teams_hiring__0e9c3f_idx'),
        ),
    ]
