# Generated by Django 5.2.7 on 2025-10-30 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_job', '0006_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name_plural': 'Job Listings'},
        ),
        migrations.AlterModelOptions(
            name='job_types',
            options={'verbose_name_plural': 'Job Types'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'Skills'},
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create_job.department'),
        ),
        migrations.AlterField(
            model_name='job',
            name='Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='Job_Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create_job.job_types'),
        ),
        migrations.AlterField(
            model_name='job',
            name='Skills_Required',
            field=models.ManyToManyField(blank=True, to='create_job.skills'),
        ),
        migrations.AlterModelTable(
            name='job_types',
            table='job_types',
        ),
    ]
