# Generated by Django 5.2.7 on 2025-11-05 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_job', '0006_teams_hiring_manager_teams_hr_team_members_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='teams',
            name='Teams_name_4fe85c_idx',
        ),
        migrations.RemoveIndex(
            model_name='teams',
            name='Teams_departm_76306d_idx',
        ),
        migrations.RemoveIndex(
            model_name='teams',
            name='Teams_manager_56c5a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='teams',
            name='Teams_hiring__0e9c3f_idx',
        ),
    ]
