# Generated by Django 5.2.7 on 2025-10-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_job', '0007_alter_department_options_alter_job_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='Job_Type',
        ),
        migrations.AlterField(
            model_name='job',
            name='Skills_Required',
            field=models.ManyToManyField(blank=True, null=True, to='create_job.skills'),
        ),
    ]
