# Generated by Django 5.2.7 on 2025-11-06 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_job', '0007_remove_teams_teams_name_4fe85c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='hiring_manager',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='hr_team_members',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='manager',
        ),
        migrations.AddField(
            model_name='add_job',
            name='hiring_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_as_hiring_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='add_job',
            name='hr_team_members',
            field=models.ManyToManyField(blank=True, related_name='jobs_as_hr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='add_job',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='add_job',
            index=models.Index(fields=['manager', 'is_active'], name='add_job_manager_1c9c65_idx'),
        ),
        migrations.AddIndex(
            model_name='add_job',
            index=models.Index(fields=['hiring_manager', 'is_active'], name='add_job_hiring__fb0053_idx'),
        ),
    ]
