# Generated by Django 5.2.7 on 2025-10-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_job', '0008_remove_job_job_type_alter_job_skills_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Job_Type',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
