# Generated by Django 5.2.7 on 2025-11-06 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_job', '0008_remove_teams_hiring_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='add_job',
            name='last_hiring_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='add_job',
            name='skills_required',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='create_job.skills'),
        ),
        migrations.AlterField(
            model_name='add_job',
            name='hr_team_members',
            field=models.ManyToManyField(blank=True, null=True, related_name='jobs_as_hr', to=settings.AUTH_USER_MODEL),
        ),
    ]
