# Generated by Django 5.2.7 on 2025-11-07 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_job', '0009_add_job_last_hiring_date_add_job_skills_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_job',
            name='hr_team_members',
            field=models.ManyToManyField(related_name='jobs_as_hr', to=settings.AUTH_USER_MODEL),
        ),
    ]
