# Generated by Django 5.2.7 on 2025-10-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_job', '0009_job_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='Department',
        ),
        migrations.DeleteModel(
            name='Job_types',
        ),
        migrations.AlterModelOptions(
            name='job',
            options={},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={},
        ),
        migrations.RemoveField(
            model_name='job',
            name='Target_hire_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='job',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='job',
            name='Description',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='Job_Type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='Skills_Required',
            field=models.ManyToManyField(related_name='jobs', to='create_job.skills'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
