# Generated by Django 5.2.7 on 2025-10-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_job', '0010_remove_job_department_delete_job_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Description',
            field=models.TextField(),
        ),
    ]
