# Generated by Django 5.2.7 on 2025-11-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_job', '0010_alter_add_job_hr_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_job',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
