# Generated by Django 5.2.7 on 2025-10-31 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_job', '0012_department_job_types_job_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Experience_In_Years',
            field=models.IntegerField(db_index=True),
        ),
    ]
