# Generated by Django 5.2.7 on 2025-10-31 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_job', '0013_alter_job_experience_in_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Targerted_Hiring_Date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
