# Generated by Django 5.2.7 on 2025-11-04 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_job', '0015_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='Location_types',
            field=models.ManyToManyField(related_name='departments', to='create_job.location'),
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('department_types', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create_job.department')),
            ],
            options={
                'db_table': 'Teams',
            },
        ),
    ]
