# Generated by Django 5.2.7 on 2025-11-04 09:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_job', '0016_department_location_types_teams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='job_types',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='job_types',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job_types',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='Location_types',
            field=models.ManyToManyField(blank=True, related_name='departments', to='create_job.location'),
        ),
        migrations.AlterField(
            model_name='job',
            name='Experience_In_Years',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='Job_Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='create_job.job_types'),
        ),
        migrations.AlterField(
            model_name='job',
            name='Skills_Required',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='create_job.skills'),
        ),
        migrations.AlterField(
            model_name='job',
            name='Targerted_Hiring_Date',
            field=models.DateField(blank=True, db_index=True, help_text='(typo kept for backward compatibility) Targeted hiring date.', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='create_job.department'),
        ),
        migrations.AlterField(
            model_name='job',
            name='no_of_opening',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='teams',
            name='department_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='create_job.department'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['Job_Title'], name='job_listing_Job_Tit_dc1869_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['Experience_In_Years'], name='job_listing_Experie_a50985_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['Job_Location'], name='job_listing_Job_Loc_7c95ff_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['Targerted_Hiring_Date'], name='job_listing_Targert_c146b2_idx'),
        ),
    ]
