# Generated by Django 5.2.7 on 2025-10-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_form_work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleformresponse',
            name='current_sattus',
            field=models.CharField(default='Scouting', max_length=50),
        ),
    ]
