# Generated by Django 5.2.7 on 2025-10-16 11:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(blank=True, db_index=True, help_text='Role/form identifier (slug)', max_length=150)),
                ('form_data', models.JSONField(default=dict, help_text='Raw form submission JSON')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_phase', models.CharField(choices=[('first_round', 'First Round'), ('second_round', 'Second Round'), ('third_round', 'Third Round'), ('hired', 'Hired'), ('rejected', 'Rejected')], db_index=True, default='first_round', max_length=50)),
                ('status', models.CharField(db_index=True, default='submitted', max_length=30)),
                ('last_action_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_submissions', to=settings.AUTH_USER_MODEL)),
                ('field_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('last_action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_phase', models.CharField(blank=True, choices=[('first_round', 'First Round'), ('second_round', 'Second Round'), ('third_round', 'Third Round'), ('hired', 'Hired'), ('rejected', 'Rejected')], max_length=50, null=True)),
                ('to_phase', models.CharField(choices=[('first_round', 'First Round'), ('second_round', 'Second Round'), ('third_round', 'Third Round'), ('hired', 'Hired'), ('rejected', 'Rejected')], max_length=50)),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('phase_change', 'Phase Change'), ('assigned', 'Assigned'), ('rollback', 'Rollback'), ('comment', 'Comment')], default='phase_change', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='candidate_form.applicationform')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='applicationform',
            index=models.Index(fields=['status', 'created_at'], name='candidate_f_status_bd0b12_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationform',
            index=models.Index(fields=['current_phase'], name='candidate_f_current_1f3879_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationstatushistory',
            index=models.Index(fields=['submission', 'created_at'], name='candidate_f_submiss_a0516c_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationstatushistory',
            index=models.Index(fields=['to_phase'], name='candidate_f_to_phas_7dffc8_idx'),
        ),
    ]
