# Generated by Django 5.2.7 on 2025-10-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationform',
            old_name='field_by',
            new_name='submitted_by',
        ),
    ]
