# Generated by Django 5.2.7 on 2025-10-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlesheet',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='googlesheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='googlesheet',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheet',
            name='spreadsheet_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='googlesheet',
            index=models.Index(fields=['name'], name='google_shee_name_f79094_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheet',
            index=models.Index(fields=['spreadsheet_id'], name='google_shee_spreads_2fd6d6_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheet',
            index=models.Index(fields=['created_at'], name='google_shee_created_731fd7_idx'),
        ),
    ]
