# Generated by Django 5.2.7 on 2025-10-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sheet', '0002_alter_googlesheet_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hiring_process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('google_sheet', 'Google Sheet'), ('typeform', 'Typeform'), ('surveymonkey', 'SurveyMonkey')], db_index=True, max_length=50)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('identifier', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='GoogleSheet',
        ),
        migrations.AddIndex(
            model_name='hiring_process',
            index=models.Index(fields=['integration_type'], name='google_shee_integra_6b61cd_idx'),
        ),
        migrations.AddIndex(
            model_name='hiring_process',
            index=models.Index(fields=['name'], name='google_shee_name_78ce3f_idx'),
        ),
        migrations.AddIndex(
            model_name='hiring_process',
            index=models.Index(fields=['identifier'], name='google_shee_identif_1fcfad_idx'),
        ),
        migrations.AddIndex(
            model_name='hiring_process',
            index=models.Index(fields=['created_at'], name='google_shee_created_23265b_idx'),
        ),
    ]
