# Generated by Django 5.2.7 on 2025-10-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sheet', '0003_hiring_process_delete_googlesheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiring_process',
            name='Token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
