# Generated by Django 5.2.7 on 2025-10-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_sheet', '0004_hiring_process_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiring_process',
            old_name='Token',
            new_name='token',
        ),
    ]
