# Generated by Django 5.2.7 on 2025-10-08 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sheet', '0005_rename_token_hiring_process_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeformAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_id', models.CharField(db_index=True, max_length=255)),
                ('answers', models.JSONField()),
                ('landed_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typeform_answers', to='google_sheet.hiring_process')),
            ],
        ),
    ]
