# Generated by Django 5.2.7 on 2025-10-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sheet', '0006_typeformanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeformanswer',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
