# Generated by Django 5.2.7 on 2025-10-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sheet', '0007_alter_typeformanswer_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeformanswer',
            name='answers',
            field=models.JSONField(),
        ),
    ]
