# Generated by Django 5.2.7 on 2025-10-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sheet', '0008_alter_typeformanswer_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeformanswer',
            name='answers',
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='bdd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='bdd_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='cucumber',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='cucumber_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='discrete_mathematics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='discrete_mathematics_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='highest_degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='job_responsibilities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='joining_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='language',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='linear_programming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='linear_programming_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='machine_learning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='machine_learning_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='notice_period',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='percentage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='python',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='python_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='r_language',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='r_language_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='rave_developer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='rave_developer_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='rdbms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='rdbms_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='statistics_probability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='statistics_probability_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='typeformanswer',
            name='unmapped_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
