# Generated by Django 5.2.7 on 2025-10-18 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_userprofile_role_alter_userprofile_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUser',
            fields=[
            ],
            options={
                'verbose_name': 'ExternalUser',
                'verbose_name_plural': 'ExternalUsers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('superadmin.userprofile',),
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
            ],
            options={
                'verbose_name': 'HR',
                'verbose_name_plural': 'HRs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('superadmin.userprofile',),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Managers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('superadmin.userprofile',),
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'SuperAdmin',
                'verbose_name_plural': 'SuperAdmins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('superadmin.userprofile',),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_by_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_by_superadmin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superadmin_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Manager', 'Manager'), ('HR', 'HR'), ('ExternalUser', 'ExternalUser')], default='ExternalUser', max_length=20),
        ),
    ]
