# Generated by Django 5.2.7 on 2025-11-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_alter_userprofile_options_alter_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='otp',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
