# Generated by Django 5.2.7 on 2025-11-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_alter_userprofile_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='hiring_managerUser',
            fields=[
            ],
            options={
                'verbose_name': 'hiring_managerUser',
                'verbose_name_plural': 'hiring_managerUser',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('superadmin.userprofile',),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Manager', 'Manager'), ('HR', 'HR'), ('ExternalUser', 'ExternalUser'), ('Hiring Manager', 'Hiring Manager')], db_index=True, default='ExternalUser', max_length=20),
        ),
    ]
