# Generated by Django 5.2.7 on 2025-11-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_hiring_manageruser_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Manager', 'Manager'), ('HR', 'HR'), ('ExternalUser', 'ExternalUser'), ('HiringManager', 'HiringManager')], db_index=True, default='ExternalUser', max_length=20),
        ),
    ]
