# Generated by Django 5.2.7 on 2025-11-03 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_data', '0004_alter_formdata_options_and_more'),
        ('tasks', '0002_alter_task_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='form_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='form_data.formdata'),
        ),
    ]
