# Generated by Django 5.2.7 on 2025-10-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='cv_upload',
            field=models.FileField(blank=True, null=True, upload_to='cv_uploads/'),
        ),
    ]
