# Generated by Django 5.2.7 on 2025-10-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_data', '0002_formdata_cv_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='candidate_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='interviewer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='meeting_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='meeting_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
