# Generated by Django 5.2.7 on 2025-11-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_data', '0003_formdata_candidate_email_formdata_interviewer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formdata',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddIndex(
            model_name='formdata',
            index=models.Index(fields=['form_name'], name='form_data_f_form_na_ec9a30_idx'),
        ),
        migrations.AddIndex(
            model_name='formdata',
            index=models.Index(fields=['submitted_at'], name='form_data_f_submitt_7f5405_idx'),
        ),
        migrations.AddIndex(
            model_name='formdata',
            index=models.Index(fields=['candidate_email'], name='form_data_f_candida_3561b2_idx'),
        ),
    ]
