# Generated by Django 5.2.7 on 2025-10-09 10:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('google_sheet', '0008_alter_typeformanswer_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('scouting', 'Scouting'), ('ongoing', 'Ongoing'), ('hired', 'Hired'), ('recycle', 'Recycle')], db_index=True, default='scouting', max_length=20)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('offer_letter_given', models.BooleanField(default=False)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('TypeformAnswer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_details', to='google_sheet.typeformanswer')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='profile_details.candidatedetails')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='candidatedetails',
            index=models.Index(fields=['current_status'], name='profile_det_current_396c79_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatedetails',
            index=models.Index(fields=['created_at'], name='profile_det_created_52e135_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatestatushistory',
            index=models.Index(fields=['previous_status'], name='profile_det_previou_d5adcc_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatestatushistory',
            index=models.Index(fields=['new_status'], name='profile_det_new_sta_39db35_idx'),
        ),
    ]
