# Generated by Django 5.2.7 on 2025-10-14 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sheet', '0009_remove_typeformanswer_answers_typeformanswer_bdd_and_more'),
        ('profile_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedetails',
            name='TypeformAnswer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='google_sheet.typeformanswer'),
        ),
    ]
