# Generated by Django 5.2.7 on 2025-10-15 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_form_work', '0002_googleformresponse_current_sattus'),
        ('profile_details', '0002_alter_candidatedetails_typeformanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedetails',
            name='TypeformAnswer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='google_form_work.googleformresponse'),
        ),
    ]
